; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:host]
platform = native
framework = 
test_framework = googletest
test_build_src = no ; Don't build the src directory (native code) for host unit tests 
lib_ignore = Logger
lib_deps = 
	google/googletest@^1.15.2
	https://github.com/meekrosoft/fff.git
build_flags = -DUNIT_TEST -fprofile-arcs -ftest-coverage -lgcov -std=c++20 -I ${PROJECT_DIR}/include -I ${PROJECT_DIR}/lib/Logger/include 

[env:device]
platform = espressif32@6.12.0
board = seeed_xiao_esp32c3
framework = espidf
platform_packages =
	platformio/framework-espidf@3.50500.0
	platformio/tool-cmake@3.30.2
	platformio/tool-esp-rom-elfs@0.0.1+20241011
	platformio/tool-esptoolpy@2.40900.250804
	platformio/tool-mkfatfs@2.0.1
	platformio/tool-mklittlefs@1.203.210628
	platformio/tool-mkspiffs@2.230.0
	platformio/tool-ninja@1.7.1
	espressif/tool-riscv32-esp-elf-gdb@12.1.0+20221002
	espressif/tool-xtensa-esp-elf-gdb@12.1.0+20221002
	platformio/toolchain-esp32ulp@1.23800.240113
	platformio/toolchain-riscv32-esp@14.2.0+20241119
check_tool = clangtidy
check_flags = clangtidy: --checks=*
; PROCESS_SIGNAL: remove flag to transmit raw data directly and analyze signal offline on the host
; build_flags = -I ${PROJECT_DIR}/include
build_flags = -I ${PROJECT_DIR}/include -DPROCESS_SIGNAL
